pluginManagement {
    repositories {
        maven { url = "https://fabricmc.net" }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    // Меняем строгий FAIL_ON_PROJECT_REPOS на компромиссный PREFER_SETTINGS, 
    // чтобы дать Fabric Loom право создавать локальные репозитории маппингов
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        maven { url = "https://fabricmc.net" }
        maven { url = "https://terraformersmc.com" }
    }
}

rootProject.name = 'midpoint_visuals'
