pluginManagement {
    repositories {
        maven { url = "https://fabricmc.net" }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = "https://fabricmc.net" }
        maven { url = "https://terraformersmc.com" }
    }
}

rootProject.name = 'midpoint_visuals'
